OpenTelemetry Exporter typedoc and exporter options update
Azure/azure-sdk-for-python pull request #15654
Opened 2020-12-04 20:30 UTC by hectorhdzg

Adding exporter options as explicit parameter
Fixing issues with typedoc return types

2020-12-09 16:29 UTC, lzchen commented on sdk/monitor/microsoft-opentelemetry-exporter-azuremonitor/microsoft/opentelemetry/exporter/azuremonitor/export/_base.py
> +            options.connection_string if options is not None else None)
I think we want to fast fail if connection string is empty or not supplied.

2020-12-09 16:34 UTC, lzchen commented on sdk/monitor/microsoft-opentelemetry-exporter-azuremonitor/microsoft/opentelemetry/exporter/azuremonitor/export/_base.py
> +    def __init__(self, options: ExporterOptions = None, **kwargs):
We want users to be able to do:
1. AzureSpanExporter(connection_string=...)
2. AzureSpanExporter() <-- connection string/ikey from env var
3. AzureSpanExporter(connection_string=..., <other-kwargs-used-by-azure-core-classes)
4. AzureSpanExporter(<other-kwargs-used-by-azure-core-classes) <-- connection string/ikey from env var

Are all these possible with this signature?

2020-12-30 19:31 UTC, lmazuel requested changes
Do NOT use type comment annotations. Your code is Python 3 only, comment type annotations are here solely for Python 2.7 compatibility.

2021-01-05 19:36 UTC, hectorhdzg commented
Closing this as is apparently not needed, added Python 2 style comment annotations to have better results while running apistub

2021-01-05 19:36 UTC, closed without merging