shared_requirements msrest verison update
Azure/azure-sdk-for-python pull request #17938
Opened 2021-04-09 08:00 UTC by RAY-316

shared_requirements msrest verison update

2021-04-09 09:20 UTC, msyyc approved these changes

2021-04-09 09:20 UTC, msyyc commented
/check-enforcer override

2021-04-09 09:20 UTC, msyyc commented
/check-enforcer override

2021-04-09 09:42 UTC, jsntcy requested changes
Hold on to not merge before confirm with @scbedd if this change will not affect other CI jobs.

2021-04-14 02:30 UTC, msyyc approved these changes

2021-04-14 03:27 UTC, jsntcy approved these changes

2021-04-14 03:28 UTC, jsntcy commented
/check-enforcer evaluate

2021-04-14 04:23 UTC, jsntcy commented
/azp run

2021-04-14 06:57 UTC, jsntcy commented
/check-enforcer evaluate

2021-04-14 07:17 UTC, jsntcy commented
/check-enforcer override

2021-04-14 09:03 UTC, merged