[AppConfig] enable samples
Azure/azure-sdk-for-python pull request #18857
Opened 2021-05-21 14:52 UTC by seankane-msft

2021-05-21 14:53 UTC, seankane-msft commented
/azp run python - appconfiguration - tests

2021-05-21 15:57 UTC, kristapratico approved these changes

2021-05-24 18:53 UTC, benbp commented on sdk/appconfiguration/tests.yml
> +      TestSamples: true
Yes, that PR has been merged, so this needs to be changed.

2021-05-24 18:53 UTC, benbp requested changes

2021-05-24 18:53 UTC, benbp commented on sdk/appconfiguration/tests.yml
> +      TestSamples: true
```suggestion
      MatrixReplace:
        - TestSamples=.*/true
```

2021-05-25 18:03 UTC, benbp approved these changes

2021-06-02 15:09 UTC, seankane-msft commented
/check-enforcer override

2021-06-02 20:52 UTC, seankane-msft commented
/check-enforcer override

2021-06-08 17:44 UTC, seankane-msft commented
/check-enforcer reset

2021-06-17 14:50 UTC, seankane-msft commented
/check-enforcer reset

2021-06-17 16:28 UTC, merged