Updates api version
Azure/azure-sdk-for-python pull request #22252
Opened 2021-12-22 15:47 UTC by automagically

# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](../CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

2022-01-12 16:28 UTC, lucasrsant requested changes

2022-01-12 16:52 UTC, automagically commented on sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/_generated/operations/_phone_numbers_operations.py
> +        request.set_json_body(_content)
In the autorest version this code was generated there was a bug where it didn't include the Content-length header, this function call was a manual intervention to keep going with the pr while the autorest was being fixed. That said, I've tested the change you proposed and indeed it fixes the issue without calling any 'request' method, furthermore, on the new version of autorest this issue has been fixed, I am  going to re-generate the code in my next commit

2022-01-12 17:07 UTC, automagically commented on sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/_generated/aio/operations/_phone_numbers_operations.py
> +        request.set_json_body(_content)
See other comment for my reply

2022-01-13 21:43 UTC, lucasrsant requested changes

2022-01-13 22:06 UTC, automagically commented on sdk/communication/azure-communication-phonenumbers/CHANGELOG.md
> +- Adds support for API verion `2022-01-11-preview2`
Done

2022-01-17 20:16 UTC, lucasrsant requested changes

2022-01-17 20:16 UTC, lucasrsant commented on sdk/communication/azure-communication-phonenumbers/CHANGELOG.md
> +- Adds support for API verion `2022-01-11-preview2`
Sorry for the last minute change, but the first phrase should be replaced by: `Support of Denmark (DK) and United Kingdom (GB) phone number acquisitions.`

2022-01-17 20:37 UTC, lucasrsant approved these changes

2022-01-17 20:49 UTC, automagically commented on sdk/communication/azure-communication-phonenumbers/CHANGELOG.md
> +- Adds support for API verion `2022-01-11-preview2`
Change log updated

2022-01-18 18:32 UTC, danielortega-msft approved these changes

2022-01-19 21:29 UTC, whisper6284 approved these changes

2022-01-19 21:29 UTC, merged