Application insights migration guide
Azure/azure-sdk-for-python pull request #23002
Opened 2022-02-10 01:42 UTC by rakshith91

2022-02-10 15:30 UTC, scottaddie requested changes

2022-02-10 15:30 UTC, scottaddie commented on sdk/monitor/azure-monitor-query/migration_guide_app_insights.md
> +This guide assists you in the migration from [azure-applicationinsights ](https://pypi.org/project/azure-applicationinsights /) v0.1.0 to [azure-monitor-query](https://pypi.org/project/azure-monitor-
```suggestion
This guide assists you in the migration from [azure-applicationinsights](https://pypi.org/project/azure-applicationinsights/) v0.1.0 to [azure-monitor-query](https://pypi.org/project/azure-monitor-query/) v1.0.x. Side-by-side comparisons are provided for similar operations between the two packages.
```

2022-02-10 15:30 UTC, scottaddie commented on sdk/monitor/azure-monitor-query/migration_guide_app_insights.md
> +To provide a more intuitive experience, the top-level client to `ApplicationInsightsDataClient` has been split into tow different clients:
```suggestion
To provide a more intuitive experience, the top-level client to `ApplicationInsightsDataClient` has been split into two different clients:

```

2022-02-10 15:30 UTC, scottaddie commented on sdk/monitor/azure-monitor-query/migration_guide_app_insights.md
> +Both of these clients can be authenticated using Azure AD.
```suggestion
- [LogsQueryClient](https://docs.microsoft.com/python/api/azure-monitor-query/azure.monitor.query.logsqueryclient?view=azure-python) serves as a single point of entry to execute a single Kusto query or a batch of Kusto queries.
- [MetricsQueryClient](https://docs.microsoft.com/python/api/azure-monitor-query/azure.monitor.query.metricsqueryclient?view=azure-python) is used to query metrics, list metric namespaces, and to list metric definitions.

Both clients can be authenticated using Azure AD.
```

2022-02-10 15:30 UTC, scottaddie commented on sdk/monitor/azure-monitor-query/migration_guide_app_insights.md
> +In `azure-applicationinsights ` v0.1.0:
```suggestion
In `azure-applicationinsights` v0.1.0:
```

2022-02-10 15:30 UTC, scottaddie commented on sdk/monitor/azure-monitor-query/migration_guide_app_insights.md
> +### A Note about the events API
```suggestion
### A note about the Events API
```

2022-02-10 15:30 UTC, scottaddie commented on sdk/monitor/azure-monitor-query/migration_guide_app_insights.md
> +***It is important to note that the Events API is just a different "API head" on the same data. It allows to query some logs in App Insights without writing Kusto queries. The API translates to Kusto
```suggestion
The `azure-applicationinsights` package includes an Events API. Note that the Events API is just a different "API head" on the same logs data. It enables the querying of some logs in Application Insights without writing Kusto queries. The API translates to Kusto queries in the background. The same data can be accessed via regular Kusto queries, as shown in the preceding example.
```

2022-02-10 15:30 UTC, scottaddie commented on sdk/monitor/azure-monitor-query/migration_guide_app_insights.md
> +In `azure-applicationinsights ` v0.1.0:
```suggestion
In `azure-applicationinsights` v0.1.0:
```

2022-02-10 22:49 UTC, scottaddie approved these changes
Looks good after considering this last batch of suggestions.

2022-02-10 23:22 UTC, scottaddie commented on sdk/monitor/azure-monitor-query/migration_guide_app_insights.md
> +    - [Send a single query request](#sending-a-single-query-request)
```suggestion
- [Migration benefits](#migration-benefits)
  - [Cross-service SDK improvements](#cross-service-sdk-improvements)
  - [New features](#new-features)
- [Important changes](#important-changes)
  - [The client](#the-client)
  - [Client constructors and authentication](#client-constructors-and-authentication)
  - [Send a single query request](#sending-a-single-query-request)
```

2022-02-11 00:09 UTC, swathipil approved these changes

2022-02-11 01:22 UTC, rakshith91 commented
/check-enforcer override

2022-02-11 01:22 UTC, merged