[change_log] write a script for change_log
Azure/azure-sdk-for-python pull request #23952
Opened 2022-04-12 06:34 UTC by kazrael2119

Write a script for change_log to show the result of change_log
https://github.com/Azure/azure-sdk-for-python/issues/23864

2022-04-12 07:00 UTC, BigCat20196 commented on scripts/test_Change_Log_info/main.py
> +    sp.call(fr"docker start Change_log")
I think we don't need fr

2022-04-12 07:02 UTC, BigCat20196 commented on scripts/test_Change_Log_info/main.py
> +        package_path=str(package[1])
why use str()? Aren't they strings? You can merge them into one line.

2022-04-12 07:06 UTC, BigCat20196 commented on scripts/test_Change_Log_info/main.py
> +                        )
Repeated code can encapsulate them into functions

2022-04-12 07:06 UTC, BigCat20196 commented on scripts/test_Change_Log_info/main.py
> +
Blank lines can be deleted, which shall comply with PEP8

2022-04-13 07:50 UTC, msyyc requested changes

2022-04-13 07:50 UTC, msyyc commented on scripts/test_Change_Log_info/README.md
> +This script will use docker and help you generate two code_reports which generate by the latest two versions of azure MGMT package on pypi..
It is better to optimize the description.

2022-04-13 07:50 UTC, msyyc commented on scripts/test_Change_Log_info/README.md
> +
Add `# preprequisites` like 
https://github.com/Azure/azure-sdk-for-python/wiki/Dataplane-Codegen-Quick-Start#prerequisites) to give more details about what need before running the tool

2022-04-13 07:50 UTC, msyyc commented on scripts/test_Change_Log_info/README.md
> +python main.py
change the folder name from `test_Cahnge_Log_info` to `check_change_log`

2022-04-13 07:50 UTC, msyyc commented on scripts/test_Change_Log_info/main.py
> +package_info = [('powerbiembedded', 'powerbiembedded'), ('signalr', 'signalr'), ('attestation', 'attestation'),
use `glob.glob` to scan `sdk/*` to get `package_info`

2022-04-13 07:50 UTC, msyyc commented on scripts/test_Change_Log_info/main.py
> +    docker_path = env.split("\scripts")[0]
it may not work in Linux. So try `pathlib.Path`

2022-04-13 07:50 UTC, msyyc commented on scripts/test_Change_Log_info/main.py
> +        # sp.call(fr'docker exec -it Change_log /bin/bash -c "cd _/sdk/{package_name}/azure-mgmt-{package_path} && pip install e ."')
remove unused comment

2022-04-13 07:50 UTC, msyyc commented on scripts/test_Change_Log_info/main.py
> +            version = versions[-1]
just `continue` if only one version

2022-04-13 07:50 UTC, msyyc commented on scripts/test_Change_Log_info/main.py
> +def findReportName(result):
in python, the function name format is `xx_xx_xx` not `abcAbcAbc`

2022-04-13 07:51 UTC, msyyc commented on scripts/test_Change_Log_info/main.py
> +    sp.call(f'docker stop Change_log')
refactor the `main` for better code structure

2022-04-15 02:17 UTC, msyyc commented on scripts/check_change_log/main.py
> +        time.sleep(10)
why sleep?

2022-04-15 02:18 UTC, msyyc commented on scripts/check_change_log/main.py
> +    file.close()
try `with open() ...`

2022-04-18 02:06 UTC, msyyc commented on scripts/check_change_log/main.py
> +    in_files = glob.glob(f'{docker_path}\sdk\*\*mgmt*')
we need to be compatible with Linux. try:
`glob.glob(str(Path(f'{docker_path}/sdk/*/azure-mgmt-*')))`

2022-04-18 02:06 UTC, msyyc commented on scripts/check_change_log/main.py
> +        service_name = mgmt_path_list[5]
[3] and [5] make the logic weird. Try to optimize it

2022-04-18 02:10 UTC, msyyc commented on scripts/check_change_log/main.py
> +            info = create_code_report(cmd_cl2)
optimize the var name to make the logic clearer.

2022-04-18 07:59 UTC, msyyc commented on scripts/check_change_log/main.py
> +        t = i.split('\\\\')
if run it in Linux, the split will not work.

2022-04-18 08:00 UTC, msyyc commented on scripts/check_change_log/main.py
> +            version = versions[-2]
I think `older_version` is better

2022-04-18 08:01 UTC, msyyc commented on scripts/check_change_log/main.py
> +            cmd_cl2 = fr'docker exec -it Change_log /bin/bash -c "cd _/ && python -m packaging_tools.code_report {service_name} --version={version}"'
cmd_cl with number is not very good name

2022-04-18 08:03 UTC, msyyc commented on scripts/check_change_log/main.py
> +            route = find_report_name(code_report_info)
rout_last_version, rout_older_version

2022-04-18 08:06 UTC, msyyc commented on scripts/check_change_log/main.py
> +def write_txt(foldor, text_name, text, version1, version2):
which version stands for older version? version1 or version2?
try to use more meaningful name

2022-04-18 08:09 UTC, msyyc commented on scripts/check_change_log/main.py
> +    merged = 'merged_report'
both var are pattern. I think it is better to be `single_api_pattern` and `multi_api_pattern`

2022-04-18 08:17 UTC, msyyc commented on scripts/check_change_log/main.py
> +    return info_output.split('\n')
info.returncode is not 0, we need to record it since it needs attention

2022-04-18 08:19 UTC, msyyc commented on scripts/check_change_log/main.py
> +            change_log_foldor_path = str(env) + r"\Change_Log"
if we run it in Linux,

2022-04-18 08:21 UTC, msyyc commented on scripts/check_change_log/main.py
> +    print("txt create successful")
what `txt` stands for? it is better to record details

2022-04-18 08:22 UTC, msyyc commented on scripts/check_change_log/main.py
> +
surplus logic

2022-05-09 08:02 UTC, msyyc commented on scripts/check_change_log/main.py
> +        versions = [str(v) for v in client.get_ordered_versions(f"{service_name}")]
```suggestion
        versions = [str(v) for v in client.get_ordered_versions(f"{service_name}")]
```
why f"{service_name}" ?

2022-05-09 08:02 UTC, msyyc commented on scripts/check_change_log/main.py
> +    print("change_log.txt create successful")
```suggestion
    with open(file=path, mode="w", encoding="utf-8") as file:
        file.write(text)
    print("change_log.txt create successful")
```

2022-05-09 08:02 UTC, msyyc commented on scripts/check_change_log/main.py
> +    sp.call(f'docker stop Change_log')
try to run the script locally and maybe you could find more to optimize

2022-05-09 08:04 UTC, msyyc commented on scripts/check_change_log/README.md
> +pip -e ../../tools/azure-sdk-tools
pip install -r requirements.txt

2022-05-11 08:48 UTC, msyyc approved these changes

2022-05-11 08:48 UTC, msyyc commented
/check-enforcer override

2022-05-11 08:48 UTC, merged