Create test_crud_async.py
Azure/azure-sdk-for-python pull request #24166
Opened 2022-04-25 15:04 UTC by JericHunter

Created an asynchronous version of tests for the CRUD test in the Cosmos SDK.

2022-04-27 22:03 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        offer = created_db.read_offer()
missing await here

2022-04-27 22:03 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        offer = created_db.replace_throughput(new_offer_throughput)
miissing await

2022-04-27 22:08 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        cls.database = await cls.client.create_database_if_nflot_exists(test_config._test_config.TEST_DATABASE_ID)
misspelled

2022-04-27 22:08 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        created_db = self.databaseForTest
we changed this name up top to just be database

2022-04-27 22:09 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        created_collection = created_db.create_container(id=collection_id,
missing await

2022-04-27 22:10 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        created_properties = created_collection.read()
missing await

2022-04-27 22:10 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        created_db.delete_container(created_collection.id)
missing await

2022-04-27 22:10 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        container_proxy = created_db.create_container_if_not_exists(id=created_collection.id,
missing await

2022-04-27 22:11 UTC, simorenoh requested changes
Missing too many awaits still - please take your time to double check these things

2022-04-29 18:25 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        cls.databaseForTest = cls.client.create_database_if_not_exists(test_config._test_config.TEST_DATABASE_ID)
still need the await here

2022-04-29 18:25 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        created_container = await created_db.get_container_client(created_collection.id)
does not need await

2022-04-29 18:27 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        read_collection.client_connection = await restricted_client.client_connection
dont need awaits, this is just changing the reference from one to the other

2022-04-29 18:28 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        change_permission = await permission.properties.copy()
doesn't need await - copy method

2022-04-29 18:28 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
>          replaced_permission = user.replace_permission(change_permission['id'], permission.properties)
missing await

2022-04-29 18:29 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        success_coll = await db.get_container_client(container=entities['coll'])
doesn't need await - get_client() methods only make an object instance, not any network calls

2022-04-29 18:30 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        db.client_connection = await old_client_connection
no need for await, just changing a reference

2022-04-29 18:30 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        change_trigger = await trigger.copy()
no need for await

2022-04-29 18:31 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        change_udf = await udf.copy()
no await needed

2022-04-29 18:32 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        change_sproc = await sproc.copy()
no need for await

2022-04-29 18:33 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
>          await self._check_default_indexing_policy_paths(collection_properties['indexingPolicy'])
doesn't need await, and method doesn't need to be async

2022-04-29 18:34 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        read_indexing_policy = await created_properties['indexingPolicy']
doesn't need await, just grabbing a property from an existing object

2022-04-29 18:37 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        root_included_path = await __get_first([included_path for included_path in indexing_policy['includedPaths']
__get_first shouldn't be async - look at what the method is doing

2022-04-29 18:37 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +                cosmos_client.CosmosClient(CRUDTests.host, CRUDTests.masterKey, "Session",
async client needs to be initialized using async with here

2022-04-29 18:38 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +            cosmos_client.CosmosClient(CRUDTests.host, CRUDTests.masterKey, "Session",
same as above

2022-04-29 18:38 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +            cosmos_client.CosmosClient(
async with here too

2022-04-29 18:39 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +            cosmos_client.CosmosClient(
same as above

2022-04-29 18:39 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +            cosmos_client.CosmosClient(
same here and line 1969

2022-04-29 18:39 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +            cosmos_client.CosmosClient(
and all client initializations below

2022-04-29 18:41 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +            collection = self.configs.create_multi_partition_collection_with_custom_pk_if_not_exist(self.client)
this needs to be a new async method - any method in the self.configs is going to be for the sync client only
I would just do
```suggestion
            collection = await self.databaseForTest.create_container(<CONFIGS>)
```
where CONFIGS are the actual name and partition key being used in the original method in the configs file

2022-04-29 18:42 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        results = await resources['coll'].read_all_items(max_item_count=2)
no need for await here - read_all_items is a query method

2022-04-29 18:42 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        results = await resources['coll'].read_all_items(max_item_count=2)
same here

2022-04-29 18:43 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        for doc in iter(results):
and this should be an async for loop over results

2022-04-29 18:43 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        results = await resources['coll'].read_all_items(max_item_count=2)
query methods dont need await

2022-05-10 16:44 UTC, simorenoh approved these changes

2022-05-11 15:21 UTC, xinlian12 commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        read_db = self.client.get_database_client(created_db.id)
Q: I thought get_database_client will only get a databaseProxy, will it also read the database?

2022-05-11 16:15 UTC, xinlian12 commented on sdk/cosmos/azure-cosmos/test/test_crud_async.py
> +        read_db = self.client.get_database_client(created_db.id)
gotcha, thanks

2022-05-13 18:00 UTC, merged