[Cosmos] change tags for Cosmos SDK team
Azure/azure-sdk-for-python pull request #25891
Opened 2022-08-26 15:38 UTC by simorenoh

Most of the issues filed for the SDK team get the tags Cosmos and Client by the azure-bot, rather than Service Attention. These changes would help us get notified faster than having to be manually checking or getting manually tagged by others.

2022-08-26 18:00 UTC, ronniegeraghty commented
@simorenoh the bot rule is not for notifying the SDK team, it is for notifying the Service Team when an issue on the SDK repos requires their attention.

2022-08-26 18:07 UTC, simorenoh commented
@ronniegeraghty so this change in the tags wouldn't change this behavior? I'm basically trying to make it so we get automatically tagged like we used to by msftbot:
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABWEAAAISCAYAAACteA2nAAAgAElEQVR4Aey9fVxU55n/3+1vf9ttd01CjCIqioIIihCfUARRQEV8AE0UiYIPRFGJgUAkJJIUFBUIDxXUxNjEJI2Jm7puY+kmjdtUGzcmaTBZl36TNZv9md1Ek6Z59iFiu7/P93WdOffMmWFmODMwOI6fP+Y1MHPmvu9znfd5mPdc57q/1ycoGHwEZgyGRY6BenAbB+Y25nbldiUDZIAMkAEyQAbIABkgA2SADJABMkAGyID/M/A9biT/30jebiMlYOXZ2zb4ucDlg9uW25YMkAEyQAbIABkgA2SADJABMkAGyAAZIAO9wwAlbABnAlPC9s5OxIMV40wGyAAZIANkgAyQATJABsgAGSADZIAMkAEy4I4BSlhKWGbJBjAD7nZ+vseTAxkgA2SADJABMkAGyAAZIANkgAyQATJABnqHAUrYABZwzITtnZ2IByvGmQyQATJABsgAGSADZIAMkAEyQAbIABkgA2TAHQOUsJSwzIQNYAbc7fx8jycHMkAGyAAZIANkgAyQATJABsgAGSADZIAM9A4DlLABLOCYCds7OxEPVowzGSADZIAMkAEyQAbIABkgA2SADJABMkAGyIA7BihhKWGZCRvADLjb+fkeTw5kgAyQATJABsgAGSADZIAMkAEyQAbIABnoHQYoYQNYwDETtnd2Ih6sGGcyQAbIABkgA2SADJABMkAGyAAZIANkgAyQAXcMUMJSwjITNoAZcLfz8z2eHMgAGSADZIAMkAEyQAbIABkgA2SADJABMtA7DFDCBrCAYyZs7+xEPFgxzmSADJABMkAGyAAZIANkgAyQATJABsgAGSAD7highKWEZSZsADPgbufnezw5kAEyQAbIABkgA2SADJABMkAGyAAZIANkoHcYoIQNYAHHTNje2Yl4sGKcyQAZIANkgAyQATJABsgAGSADZIAMkAEyQAbcMUAJSwnLTNgAZsDdzs/3eHIgA2SADJABMkAGyAAZIANkgAyQATJABshA7zBACRvAAo6ZsL2zE/FgxTiTATJABsgAGSADZIAMkAEyQAbIABkgA2SADLhjgBKWEpaZsAHMgLudn+/x5EAGyAAZIANkgAyQATJABsgAGSADZIAMkIHeYYASNoAFHDNhe2cn4sGKcSYDZIAMkAEyQAbIABkgA2SADJABMkAGyAAZcMcAJSwlLDNhA5gBdzs/3+PJgQyQATJABsgAGSADZIAMkAEyQAbIABkgA73DACVsAAs4ZsL2zk7EgxXjTAbIABkgA2SADJABMkAGyAAZIANkgAyQATLgjgFKWEpYZsIGMAPudn6+x5MDGSADZIAMkAEyQAbIABkgA2SADJABMkAGeocBStgAFnDMhO2dnYgHK8aZDJABMkAGyAAZIANkgAyQATJABsgAGSADZMAdA5SwlLDMhA1gBtzt/HyPJwcyQAbIABkgA2SADJABMkAGyAAZIANkgAz0DgOUsAEs4JgJ2zs7EQ9WjDMZIANkgAyQATJABsgAGSADZIAMkAEyQAbIgDsGKGEpYZkJG8AMuNv5+R5PDmSADJABMkAGyAAZIANkgAyQATJABsgAGegdBihhA1jAMRO2d3YiHqwYZzJABsgAGSADZIAMkAEyQAbIABkgA2SADJABdwxQwlLCMhM2gBlwt/PzPZ4cyAAZIANkgAyQATJABsgAGSADZIAMkAEy0DsMUMIGsIBjJmzv7EQ8WDHOZIAMkAEyQAbIABkgA2SADJABMkAGyAAZIAPuGKCEpYRlJmwAM+Bu5+d7PDmQATJABsgAGSADZIAMkAEyQAbIABkgA2SgdxighA1gAcdM2N7ZiXiwYpzJABkgA2SADJABMkAGyAAZIANkgAyQATJABtwxQAlLCctM2ABmwN3Oz/d4ciADZIAMkAEyQAbIABkgA2SADJABMkAGyEDvMEAJG8ACjpmwvbMT8WDFOJMBMkAGyAAZIANkgAyQATJABsgAGSADZIAMuGOAEpYSlpmwAcyAu52f7/HkQAbIABkgA2SADJABMkAGyAAZIANkgAyQgd5hgBI2gAUcM2F7ZyfiwYpxJgNkgAyQATJABsgAGSADZIAMkAEyQAbIABlwxwAlLCUsM2EDmAF3Oz/f48mBDJABMkAGyAAZIANkgAyQATJABsgAGSADvcMAJWwACzhmwvbOTsSDFeNMBsgAGSADZIAMkAEyQAbIABkgA2SADJABMuCOAUpYSlhmwgYwA+52fr7HkwMZIANkgAyQATJABsgAGSADZIAMkAEyQAZ6hwFK2AAWcMyE7Z2diAcrxpkMkAEyQAbIABkgA2SADJABMkAGyAAZIANkwB0DlLCUsMyEDWAG3O38fI8nBzJABsgAGSADZIAMkAEyQAbIABkgA2SADPQOA5SwASzgmAnbOzsRD1aMMxkgA2SADJABMkAGyAAZIANkgAyQATJABsiAOwYoYSlhmQkbwAy42/n5Hk8OZIAMkAEyQAbIABkgA2SADJABMkAGyAAZ6B0GKGEDWMAxE7Z3diIerBhnMkAGyAAZIANkgAyQATJABsgAGSADZIAMkAF3DFDCUsIyEzaAGXC38/M9nhzIABkgA2SADJABMkAGyAAZIANkgAyQATLQOwxQwgawgGMmbO/sRDxYMc5kgAyQATJABsgAGSADZIAMkAEyQAbIABkgA+4YoIQNYAmrNvwNNw9gtut1sJ3V9uYzD/pkgAyQATJABsgAGSADZIAMkAEyQAbIABnwLwYoYSnnKGjJABkgA2SADJABMkAGyAAZIANkgAyQATJABsgAGfAhA5SwPgwuf3Hwr18cuD24PcgAGSADZIAMkAEyQAbIABkgA2SADJABMkAGrgYDlLABImFv7h+K4MHDMShsJIaERyNsRAxUTVj5W16T92QZWfZqwMY+eZAjA2SADJABMkAGyAAZIANkgAyQATJABsgAGbgeGaCEvYYl7M39ByNkSISdcFXitatnEbPyWWnjegSf68wDPhkgA2SADJABMkAGyAAZIANkgAyQATJABshAbzFACXsNSlgRp5LV2pVoNfu+tEUZy4NObx102A9ZIwNkgAyQATJABsgAGSADZIAMkAEyQAauNwYoYa8xCRsyOLzH5KujpJW2r7cdgOvLgz4ZIANkgAyQATJABsgAGSADZIAMkAEyQAbIgK8ZoIS9RiRsUL9BCB0W7TMBq4Ss9CF9+Ro8ts+DGxkgA2SADJABMkAGyAAZIANkgAyQATJABsjA9cIAJew1IGFlIi3jRFtKmPrqWfryh8m7brplIG4ZMAT9Bw3DgMHh2kP+ltfkvetlJ+V68oREBsgAGSADZIAMkAEyQAbIABkgA2SADJCBa5sBSlg/l7AiQ30lW7tq92qIWDXZ2LDI0YiIinP7kGU4udi1fQDiCYTbjwyQATJABsgAGSADZIAMkAEyQAbIABm4HhighPVjCStlAXozA9ZRykrfvVWaQOTr4GEjrdJ1VUEhHnniaRz/fRv+59NP8M2Fr3D+wuf47OMzeOPEcex5Yh9WFqy3Li+f5eRiPGj7+qAdGxeBOemxWLE0HncXJOHeu6dhY5H/P2ScMl4Zt4xf1sPXsZL2R4VHYca4eCyZmoI7Z8zG+tlzUZgx77p5yPrKesv6SxwkHr0R9/CIiYgfn4kZyfmYP6sYC+eU4ba59/HBGPQYA8KUsCWMCWvCXG+wzT54nicDZIAMkAEyQAbIABm4lhmghPVjCdsbNWAdxavj/zIGXwMupQYk6zVufAIam36Cc+fO4mLHFVy4cgWXrnTg/IUv8ZcrX+LKhXP4/MM/4K3jv8YvX9iPC999if/+6EM0/qRZ+6y0IW35erxs//o66PcNDkFqSowmMQtWJmDRgnFInzEGKdNGI3FKNBImR/n9Q8Yp45VxL144DrIeImVlvWT9epLpvv0GYmrseE0+5qbMxPxJiUi5dQKSxozDpFFxmBgde908ZH1lvWX9JQ55KTO1uEh8JE49GfegfoMxNm62JsbSktZh7KhsDB88G6H90xB801T0uyGRD8agxxgQpoQtYUxYE+ZEygqDwmJPss22rq9zLrc3tzcZIANkgAyQATIQyAxQwvqphA0ZHH7VyhA4ilgZi692ApX9es+9ZTj7iUW+ioC92HEZ33VcwJXvvkTHNx/j7d/9Ew7+dCt+WlOMh+5ajE1FOfjZT+tw5r/+DRcufI5Pzn2MknvLNZkrbfpqvGz3+johTJwQibsKEpGbE4/kqdeGcDUrhadNjUZezkRsWJMIWc+eYHts5GjcmZaOxYnTkRBz63UjWz0Ry1NG34rFidOQn5YOiVdPxD1qZCLmzbwbCWOXY+At03tMtFHcUlx7wsCgvimYMm455s0sgjDZE2yzjevrnMvtze1NBsgAGSADZIAMBDoDlLB+KGHltnpHEer4f9SYCcjIWoLsvAK3j9TZC7psy7FtZ//74lb/IcOjNGn62OP78F3HJe3xzZ//F99e+Yv2958vf4VLn72PXz/XhP31d+Nn29bgsYo7sOPe2/GT+5agadMKtGy/B7/7l0OaiL343bfY+/g+rU1pO9B3Xq6fb09Qctt+4epELYPUrNi8FpdLmT5aW09Z3+4wJbfbr0qdpWV+eiIlr9dlk2LHa/GSuHUn7nIr+Oxpd2FI/zTKV2a6+gUDQ4LTkD59g1amoDts87O+PccxvowvGSADZIAMkAEyQAZ6nwFKWD+UsIPCRroVpyJgyytrUb9rn6nHPQ9shnzGmVw1+5qMqSd3UJUBe+DgQauAFRH71ZX/H+f/8md8d+kb4NJZvPL8Dux/eD12lc5D47pkPHbvPDxbmYNf/mQ96taloywvBT/ZUozT7/0eFy9/hcuXL+EfDh70KCN246HTePPUabz56tPI8kMeejLuPm8rpgAVu/ahInesSV7molA4LplrcnnPDpKRuY2o39WI7BjPPrdg/jisyp2MxMTAyn51JYllPVflTYastzeMZEycgpzkVEwazexXT6Ty5NG34o7kVEj8vIn7lPjFSJ50J4JvSvYL+eZJ1iSXDews2wFByZg2eTWEUY/YnlmhXdeYP4fYH9u9PeabG6N+vqouQCSvFTzbrowX40UGyAAZIANkgAyQAY0BSlg/A8FMFmzGgiXal5RtjXtQcv8Wtw8lakXadlfE9lQ2rKoBa8yAVZmwX//5f3Gh4yKuXPoMn/7H7/BIRR4eXj8dW5ePxc51idi3cR6e//EibMuJQ23uJFSvnI67Fk/F4Z/vwYVLf9QkrIhYlRFrpkYsJaz9l1hzX0ZdfCYAJKxkhOYvT/D7Oq+uhGp3XhcR62lGrGRyLp2WxtID3ah1KyLW04xYyYCdnrCG8pXZr37NgIhYYdX0eYUS1nysvL5+1WWy4w/5LXtRvX0r1ubORXSIi3O81312s73haVha1cUPvFFZWFHRjJoWS4JCTW0VshO7d1dUaGIeCqt2W9us39GM0oIsRAa7WB+vxjAIkVkVqG6pQLKr+PaNQnx2Bcqb9OSLlr0o3+BmHK7a4eu9sH+5YIOxZ+zJABkgA2RAZ4AS1s92hpAhEV1mrGbnrdEkrAjYrjJZlbAVGdtdEStjM/1FykVcReTKBFpSA1aJV+PzN1c6cPHS11oW7C+f2IKfFGfg/oWReLZiLl57bB0OVi5FQ+4EPFeSgSNbl+PXDeuxNmMMHrh7CS5f/NgqYUXE3lNapvXVlTymhO3BC8ZrXMJKbVQpQXC9ZMA6CltZb1l/szVipaaplCBgBmz3JhuT+EkczdaIlXqbUoKAGbCBnU0aCNnCwqiUJjBdI5YSttvXWV1fp+kStnYr1m4otz3K61C9Q0m+3SicH9MLY+ni+iNkIlIL6lCti1WXGdKxBaiQZerqsDY3B6nZRSivk3XZjcKZXl67Tiu33G1WXYUV0mZGniZ5teSGzQWI7uswdo/HMAihSXkorNZjvsuFhO07EdmbLctUlBRgTkYOsjfoMXE2DhfX311z4bA+bOfq889twG1ABsgAGQhIBihh/QzssBExXYpVTySsSNqeErEytu5exEkZgrjxCdokXEb5qv4+33ERly9/ia8/+jc0bsxG8z3pqF4ag3NH6jQJ25g/Dc+UzMPvHr4T7z5+H/7juWrsLs3GXctm4PyX/2knYc+dO6v11dVEXZSwPXjhfQ1L2L7BIdiwJinga8A6ilfH/9NSYnB3QRIkHu729779BmqTSyWNGccs2G5kwaryBcmx43HnjNmQuLqLu8w8LxMfsQYsBey1ImmHDJiJ+bOKIey6Y1t7jxK26xh1+7rVfRmg0MQClDZ0U2B2e4zBSCjYa5GgLbtR+oCUFnKVCRuDzKp9qG+oQHKo4XomdC4KZT2aSpHgKEzNjC+lAPkpnTNpo5dbxlI8N8ywrTwcQ1QeSpXwrt6qC2PnEjZ2ZbNTmRyUUIRKlzExxMHMunIZw7Zk7Lo8TpMX8kIGyAAZ6BYDlLB+BNDN/UO7FLAiVT2VsD0pYmWM3p6cVRZs3Y4duHjlAr67ch4dV77F5Y5v8N3lr3Gp42t8dQX488U/4veH6vFIaSo25YxC2y+24cW99+KB3AnYu2YmXqy5C0d3bsKB+3PxeNF8PPngcmSnj8PHn3yAC5fO49Lli1qWrTw3/KS5y2xYStgevOC8hiVsakoMcpdM9EEZgoloO1MGfLYObTVR1vYrW5Lw5H22/x1l6NX8f3nOREg83O3rU2PHY3HidArYHhCwSsQuTpoOiau7uI+Nm42Escv9+hb0a0UOcpzeiuxWHH0X+PDdM2g2WQ5iyrgVEHbdsa29RwnbdYy6fd3qXsJq2yF0EYols7ShFPHeCMxujzEYyRvklvscxA4PRh93XIwv1GRkeXbnc9aw7DpN3hbO7MHrnKhVWu37mvVptm3l6RhiVqG8tgpL08YiKGgssrVsWGcSdgqWSkav0zrEYZhVvg/1tYWI7YF4d7lvsg/b9mYsGAsyQAbIABnoBgOUsN0IXk9fsAQPHt5tCZs2eyEyspY4rf/aExmxMkZv11vKGUgpgo8+OYvvOi5oj8tXRJhewKXLIk/P4+srf8Hlrz/CjnsXYsddyXhm8yI8cMd4LJ4QhCXjb0RZajh2r52PfaV34L700diyaDy256di6Zzx+PDDP+D8xW9x8Ttp76L2fPaTs1qf7kopOJewadh4qN0yYdep17FzmX47W2gGcmsO4OBR9d5pvPl2O156YS/yE51d5Kchv/kIXnpDn/zr1GkcP3oEDRsyEGJgL+vRNr2vVmyMXIeGVv3/5zdr8bYbY2Ixdqr3T53GK61P631HYE7lIRx+Te/r7TYcfsIhM8TQp+N2DBplX0+tXq85NszZFzCpT5ZbhUprfTJLnbRhcjue08yMQYjMKEd5g8ps2YuKkjyMlUwVVxNzDU9DZkmdXS224tw0hDobz/A0ZJfZasHV127FivQYRHswMVfhnVOQlOT5RFwrtqag7e216PhERKv+OLsOnx9LwobJIlmdSNif5ujLLsUvtWX8S8ZOnToKd61OdLuvy+3zk0fHeSVhc5IW40jZFnzU1IJPW/RHQy3eW5uJO3tQaiq5ea08J8RYyhI47pvG/+ekbUDIzZyIiwLVW4HaE5/zXMIO7DsNwq6RZad/u5JtwWORWrDVds7ZtQ81VeVIjbI/7xon5pKMzuJa2zmnsqKo0/JqDJ3Of011WJshgszYvn6+chRiUelYajz/7NiN8sK5CLX7rLEd+7871x3drcnHaGNWp9aW4XwZmozMkkbr+VGrf5pg9rZ7QztuxmjJwNy [...]

2022-08-26 18:32 UTC, ronniegeraghty commented
@simorenoh Sorry, forgot the Cosmos SDK was owned by the Service Team. 
@rohit-ganguly & @lmazuel, I'll check with @jsquire once he's back to see if this will affect any other part of the triage process, but I also wanted to check with you as the language owners.

2022-08-27 14:39 UTC, jsquire requested changes
It's unusual, but it won't break any existing automation.  I'd like for us to add this as a second rule rather than changing the "Service Attention" rule, however.   There are times the management team will route management SDK issues for Swagger to the service teams.

2022-08-29 15:27 UTC, simorenoh commented
@jsquire went ahead and did those changes then, thanks!

2022-08-29 16:04 UTC, ronniegeraghty approved these changes

2022-08-29 19:15 UTC, jsquire approved these changes

2022-08-29 20:13 UTC, merged