[Communication] - azure-communication-phonenumbers - Update default polling interval value
Azure/azure-sdk-for-python pull request #27600
Opened 2022-11-18 14:18 UTC by sorrego-msft

# Description

This will set a default polling interval of 2 seconds for the functions: begin_search_available_phone_numbers, begin_purchase_phone_numbers and begin_update_phone_number_capabilities.

2022-11-21 21:22 UTC, automagically requested changes

2022-11-21 21:22 UTC, automagically commented on sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/_phone_numbers_client.py
>              for LRO operations if no Retry-After header is present.
Would be nice to take the time to document what is the unit of the polling interval e.g. seconds

2022-11-21 21:22 UTC, automagically commented on sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/_phone_numbers_client.py
> +        polling_interval = kwargs.pop('polling_interval', 2)
First of all, kudos for using the default value for the pop function, second this '2' is a magic number that would be more readable within a constant like `_DEFAULT_POLLING_INTERVAL_IN_SECONDS = 2` of course change seconds by the real unit of the pooling interval.

2022-11-22 13:30 UTC, sorrego-msft commented
> @sorrego-msft please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

2022-11-22 17:09 UTC, automagically approved these changes

2022-11-22 18:05 UTC, danielortega-msft requested changes
The change looks good, but I believe you would need to replicate it to the async client as well (sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/aio/_phone_numbers_client_async.py)

2022-11-22 19:02 UTC, danielortega-msft approved these changes

2022-11-23 17:34 UTC, merged