Add code tour for entity classes
Azure/azure-sdk-for-python pull request #27604
Opened 2022-11-18 19:03 UTC by MilesHolland

# Description

Adds a code tour describing the basics of AML entity classes. Includes a couple TODOs that are references to other tours that don't exist yet.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

2022-11-18 19:29 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2022-11-21 20:11 UTC, diondrapeck requested changes

2022-11-21 20:11 UTC, diondrapeck commented on sdk/ml/azure-ai-ml/.tours/entity_classes_purpose_and_examples.tour
> +      "description": "Another important feature of entity classes is their ability to be loaded to and from YAML. This is largely achieved by a separete set of classes call schema classes, but some b
nit for typo on "separate"

2022-11-21 20:11 UTC, diondrapeck commented on sdk/ml/azure-ai-ml/.tours/entity_classes_purpose_and_examples.tour
> +      "title": "Related DIrectory: Operations"
nit for typo, lowercase the "I" in Directory

2022-11-21 20:11 UTC, diondrapeck commented on sdk/ml/azure-ai-ml/.tours/entity_classes_purpose_and_examples.tour
> +      "description": "One of the most important features of entity classes is their ability to convert themselves to and from their corresponding autorest representations. Take a look at the function
I really like this explanation

2022-11-21 20:30 UTC, MilesHolland commented on sdk/ml/azure-ai-ml/.tours/entity_classes_purpose_and_examples.tour
> +      "description": "One of the most important features of entity classes is their ability to convert themselves to and from their corresponding autorest representations. Take a look at the function
Thanks!

2022-11-21 20:56 UTC, diondrapeck approved these changes

2022-11-21 21:40 UTC, merged