VC operations
Azure/azure-sdk-for-python pull request #28459
Opened 2023-01-24 00:33 UTC by luigiw

# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

2023-01-27 20:18 UTC, diondrapeck requested changes

2023-01-27 20:18 UTC, diondrapeck commented on sdk/ml/azure-ai-ml/azure/ai/ml/_utils/azure_reource_utils.py
> +# ---------------------------------------------------------
typo in file name - *azure_resource_utils.py

2023-01-27 20:18 UTC, diondrapeck commented on sdk/ml/azure-ai-ml/azure/ai/ml/_utils/azure_reource_utils.py
> +def get_vitual_clusters_from_subscriptions(credential: TokenCredential, subscription_list: Optional[List[str]] = None) -> List[Dict]:
typo: *get_virtual_clusters_from_subscriptions

2023-01-27 20:18 UTC, diondrapeck commented on sdk/ml/azure-ai-ml/azure/ai/ml/operations/_virtual_cluster_operations.py
> +        return get_vitual_clusters_from_subscriptions(self._credentials, subscription_list=subscription_list)
same typo from before

2023-01-31 21:22 UTC, luigiw commented on sdk/ml/azure-ai-ml/azure/ai/ml/_utils/azure_reource_utils.py
> +def get_vitual_clusters_from_subscriptions(credential: TokenCredential, subscription_list: Optional[List[str]] = None) -> List[Dict]:
Good catch. Fixed.

2023-01-31 21:22 UTC, luigiw commented on sdk/ml/azure-ai-ml/azure/ai/ml/operations/_virtual_cluster_operations.py
> +        return get_vitual_clusters_from_subscriptions(self._credentials, subscription_list=subscription_list)
Fixed.

2023-02-01 19:59 UTC, luigiw commented
@kdestin test

2023-02-02 01:31 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[azure-ai-ml](https://apiview.dev/Assemblies/Review/1ab93f576a4b40fb8380456cf03af80c)

2023-02-02 18:38 UTC, kdestin commented on sdk/ml/azure-ai-ml/setup.py
> +        "azure-mgmt-resourcegraph>=2.0.0",
Do these requirements need an upper bound?

2023-02-03 00:11 UTC, luigiw commented on sdk/ml/azure-ai-ml/tests/virtual_cluster/e2etests/test_vc.py
> +    def test_get_and_list(self, client: MLClient) -> None:
Some code was missed out in the previous commit. I committed the "get" part now.

2023-02-03 00:11 UTC, luigiw commented on sdk/ml/azure-ai-ml/tests/conftest.py
> +        ("vc_test", "marks tests as virtual cluster tests"),
Good suggestion. Changed to `virtual_cluster_test`.

2023-02-03 00:12 UTC, luigiw commented on sdk/ml/azure-ai-ml/azure/ai/ml/_utils/azure_resource_utils.py
> +def get_vc_by_id(name: str, resource_group: str, subscription_id: str, credential: TokenCredential) -> Dict:
Done.

2023-02-03 01:27 UTC, closed without merging

2023-02-03 21:09 UTC, kdestin commented on sdk/ml/azure-ai-ml/setup.py
> +        "azure-mgmt-resourcegraph>=2.0.0",
Resolved in #28624