Jiriburant/ga version of sip routing
Azure/azure-sdk-for-python pull request #29217
Opened 2023-03-08 16:35 UTC by jiriburant

# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

2023-03-08 17:22 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[azure-communication-phonenumbers](https://apiview.dev/Assemblies/Review/64850e3fb414431a85ba75f4f74cc532)

2023-03-10 22:23 UTC, danielortega-msft requested changes
Please add a changelog entry stating that the API version for the SIP client changed.

2023-03-10 22:23 UTC, danielortega-msft commented on sdk/communication/azure-communication-phonenumbers/tests.yml
> -        AZURE_TEST_RUN_LIVE: 'true'
Why was this removed?

2023-03-14 03:53 UTC, danielortega-msft approved these changes

2023-03-14 06:49 UTC, jiriburant commented on sdk/communication/azure-communication-phonenumbers/tests.yml
> -        AZURE_TEST_RUN_LIVE: 'true'
Reverted the change.

2023-03-14 09:56 UTC, merged