Expose Batch Job Resource Entity
Azure/azure-sdk-for-python pull request #29373
Opened 2023-03-15 21:46 UTC by TajiHarrisMicrosoft

# Description

Fixing batch job  entity to flatten the properties of both batch job rest object and batch job resource rest object on one entity. 

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

2023-03-15 22:26 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[azure-ai-ml](https://apiview.dev/Assemblies/Review/5541773217424739ae2f7e1071d1e6de)

2023-03-20 07:56 UTC, luigiw requested changes

2023-03-20 07:56 UTC, luigiw commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/batch_job.py
>      """
Please add docstring for the arg list.

2023-03-20 07:57 UTC, luigiw commented
Can you also add unit test cases for the from_rest() logic? The code looks good otherwise, thank you!

2023-03-27 20:56 UTC, hugoaponte requested changes

2023-03-27 20:56 UTC, hugoaponte commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/batch_job.py
> +    ):
@TajiHarrisMicrosoft: Please add SystemData here as well. Removing it would be a breaking change.

2023-08-25 08:32 UTC, closed without merging