switch tooling over to typespec
Azure/azure-sdk-for-python pull request #29501
Opened 2023-03-21 23:56 UTC by iscai-msft

# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

2023-03-22 02:18 UTC, msyyc requested changes
we shall wait for other language together and test it before merge so block it temporarily.
java: https://github.com/Azure/azure-sdk-for-java/pull/34136/files

2023-03-23 21:59 UTC, benbp commented on tools/azure-sdk-tools/packaging_tools/sdk_generator.py
> +        spec_word = "typeSpecProject"
```suggestion
        spec_word = "typespecProject"
```

2023-03-24 01:39 UTC, msyyc commented on tools/azure-sdk-tools/packaging_tools/sdk_generator.py
> +        spec_word = "typeSpecProject"
![image](https://user-images.githubusercontent.com/70930885/227402569-86b9b52c-11e9-431a-bc2f-80fc0a9d9ec3.png)

2023-03-24 01:47 UTC, msyyc approved these changes

2023-03-24 01:47 UTC, merged

2023-03-31 20:27 UTC, weshaggard commented on eng/common/scripts/Cadl-Project-Sync.ps1
> -# For details see https://github.com/Azure/azure-sdk-tools/blob/main/doc/common/Cadl-Project-Scripts.md
You should not be deleting files under `eng\common` directly in a language repo. In fact I don't know how this didn't fail as we have a CI check for this. I've filed a bug to investigate this.

2023-04-06 23:30 UTC, weshaggard commented on eng/common/scripts/Cadl-Project-Sync.ps1
> -# For details see https://github.com/Azure/azure-sdk-tools/blob/main/doc/common/Cadl-Project-Scripts.md
I got this back in sync with https://github.com/Azure/azure-sdk-tools/issues/5882