Upgrade job contract from v2023_02_01_preview to v2023_04_01_preview
Azure/azure-sdk-for-python pull request #29573
Opened 2023-03-24 18:03 UTC by chnldw

# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

2023-03-24 18:06 UTC, needuv requested changes
please don't check this in until MFE is available through ARM in all regions. All of the live testing will be broken since the operations will try to hit ARM and then fail

2023-03-24 18:11 UTC, needuv commented
If you want to test the changes in the PR in the meantime, pass the following kwarg to the April preview client:

`base_url=https://master.api/azureml-test.ms/mferp/managementfrontend/`

2023-03-24 18:49 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[azure-ai-ml](https://apiview.dev/Assemblies/Review/3c7ffc04698247ae9cf555e27eb4140a)

2023-03-24 20:25 UTC, luigiw approved these changes

2023-04-17 19:14 UTC, needuv approved these changes

2023-04-17 19:16 UTC, merged