Ikumarapeli/recording downloader
Azure/azure-sdk-for-python pull request #29604
Opened 2023-03-27 20:48 UTC by ikumarapeli-msft

# Description
Can now use the downloadStreaming and downloadTo, and delete recording methods.

2023-03-27 20:57 UTC, juntuchen-msft approved these changes

2023-03-27 21:41 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[azure-communication-callautomation](https://apiview.dev/Assemblies/Review/d8100ee037844d8aa5e5ae7bf268f053)

2023-03-28 06:26 UTC, petrsvihlik requested changes

2023-03-28 06:26 UTC, petrsvihlik commented on sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_shared/policy.py
this file needs to be copied over to the other modalities' folders

2023-04-05 15:49 UTC, ikumarapeli-msft commented on sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_shared/policy.py
created a separate PR to address that

2023-04-10 15:19 UTC, merged