Update forecasting_job.py - Added documentation for forecast job's set_training method
Azure/azure-sdk-for-python pull request #30339
Opened 2023-05-10 11:13 UTC by Nivi09

Added documentation for forecast job's set_training method.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [x] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [x] Pull request includes test coverage for the included changes.

2023-05-10 11:54 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[azure-ai-ml](https://apiview.dev/Assemblies/Review/8a087d68d0c94858890eb1010422b4cd)

2023-05-11 19:30 UTC, nick863 requested changes

2023-05-11 19:30 UTC, nick863 commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/forecasting_job.py
> +        :keyword enable_onnx_compatible_models:
Please use the tag :param: for example:
` :param enable_onnx_compatible_models:`

2023-05-11 19:30 UTC, nick863 commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/forecasting_job.py
> +        :paramtype enable_stack_ensemble: typing.Optional[bool]
`:type: bool or None`

2023-05-11 19:30 UTC, nick863 commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/forecasting_job.py
> +        :paramtype enable_vote_ensemble: typing.Optional[bool]
`:type: bool or None`

2023-05-11 19:30 UTC, nick863 commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/forecasting_job.py
> +        :paramtype ensemble_model_download_timeout: typing.Optional[int]
`:type: int or None`

2023-05-11 19:30 UTC, nick863 commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/forecasting_job.py
> +        :paramtype allowed_training_algorithms: typing.Optional[List[str]]
`:type: list(str) or None`

2023-05-11 19:30 UTC, nick863 commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/forecasting_job.py
> +        :paramtype blocked_training_algorithms: typing.Optional[List[str]]
`:type: list(str) or None`

2023-05-11 19:30 UTC, nick863 commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/forecasting_job.py
> +        :paramtype training_mode: typing.Optional[typing.Union[str, azure.ai.ml.constants.TabularTrainingMode]]
`:type: azure.ai.ml.constants.TabularTrainingMode, str or None`

2023-05-12 09:28 UTC, Nivi09 commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/forecasting_job.py
> +        :paramtype enable_onnx_compatible_models: typing.Optional[bool]
Done

2023-05-12 09:28 UTC, Nivi09 commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/forecasting_job.py
> +        :paramtype enable_model_explainability: typing.Optional[bool]
Done

2023-05-12 09:28 UTC, Nivi09 commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/forecasting_job.py
> +        :paramtype enable_stack_ensemble: typing.Optional[bool]
Done

2023-05-12 09:29 UTC, Nivi09 commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/forecasting_job.py
> +        :paramtype enable_vote_ensemble: typing.Optional[bool]
Done

2023-05-12 09:29 UTC, Nivi09 commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/forecasting_job.py
> +        :paramtype ensemble_model_download_timeout: typing.Optional[int]
Done

2023-05-12 09:29 UTC, Nivi09 commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/forecasting_job.py
> +        :paramtype allowed_training_algorithms: typing.Optional[List[str]]
Done

2023-05-12 09:29 UTC, Nivi09 commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/forecasting_job.py
> +        :paramtype blocked_training_algorithms: typing.Optional[List[str]]
Done

2023-05-12 09:30 UTC, Nivi09 commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/forecasting_job.py
> +        :paramtype training_mode: typing.Optional[typing.Union[str, azure.ai.ml.constants.TabularTrainingMode]]
Done

2023-05-12 16:12 UTC, nick863 approved these changes

2023-05-15 07:42 UTC, novaturient95 approved these changes

2023-05-15 16:12 UTC, skasturi approved these changes

2023-05-15 16:13 UTC, merged