Implement continuation token size limit
Azure/azure-sdk-for-python pull request #30600
Opened 2023-06-01 22:27 UTC by bambriz

# Description

This PR adds continuation token size limit support to the python sdk. The new option for item queries accepts a non-negative integer value and is represented in terms of KB, ie 2 is 2kb or 2048 Bytes. This PR fixes [issue #27625](https://github.com/Azure/azure-sdk-for-python/issues/27625)

sample:
 `query_iterable = container.query_items(query="SELECT * FROM c where c.some_field = 'some_value'", max_item_count=max_count, partition_key=Some_Partition_Key, response_Continuation_Token_Limit_In_Kb=8)`
 
This query will limit the continuation token size to 8KB. 

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

2023-06-01 22:43 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[azure-cosmos](https://apiview.dev/Assemblies/Review/d9734ad3263542b3a63a068e99157be1)

2023-06-02 14:06 UTC, simorenoh requested changes
Couple small comments here and there, implementation looks good overall though.

Also missing an update to the Changelog and the addition of samples to show users how the option can be used. Please add those and ask for another review, thanks!

2023-06-02 14:06 UTC, simorenoh commented on .gitignore
please re-add the empty line, we generally want our files to have one at the end

2023-06-02 14:06 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py
> +        :keyword int response_Continuation_Token_Limit_In_Kb: is used to limit the length of continuation token
let's use pythonic code here and have only lower case with underscores as opposed to camel case

2023-06-02 17:21 UTC, bambriz commented on .gitignore
The empty line is there. I just temporarily added the log files but I forgot to remove them before I made a commit so I had to make another to remove them.

2023-06-02 22:24 UTC, simorenoh commented
Seems like the pipelines are complaining but otherwise LGTM! Let's try to get other reviews so we can release this after the next stable release.

2023-06-07 18:30 UTC, bambriz commented on sdk/cosmos/azure-cosmos/azure/cosmos/container.py
> +            in the query response. Valid values are >= 0.
For the 0 value. 0 is a valid value for the backend, while negative values raise an error. The behaviour for 0 is basically the same as not passing in a value in the first place. In the other SDKs it is mentioned that valid values are >= 0, but saying non negative values is also valid.

2023-06-07 20:22 UTC, kushagraThapar requested changes
There are no tests for this feature. 
@bambriz - for every feature we add, we should aim to add tests to make sure we test it and catch future regressions.

2023-06-07 20:22 UTC, kushagraThapar commented on sdk/cosmos/azure-cosmos/azure/cosmos/container.py
> +            in the query response. Valid values are non-negative integers. A value of 0 is the same as not passing a value (default no limit).
```suggestion
            in the query response. Valid values are positive integers. A value of 0 is the same as not passing a value (default no limit).
```

2023-06-07 20:22 UTC, kushagraThapar commented on sdk/cosmos/azure-cosmos/samples/document_management.py
> +def query_items_with_continuation_token_size_limit(container, doc_id):
thanks for adding the sample :)

2023-06-07 20:48 UTC, simorenoh commented on sdk/cosmos/azure-cosmos/azure/cosmos/container.py
> +            in the query response. Valid values are non-negative integers. A value of 0 is the same as not passing a value (default no limit).
same here as above

2023-06-08 00:41 UTC, kushagraThapar approved these changes

2023-06-08 00:41 UTC, kushagraThapar commented on sdk/cosmos/azure-cosmos/CHANGELOG.md
> +* Added **provisional** ability to limit Continuation Token size. See [PR 30600](https://github.com/Azure/azure-sdk-for-python/pull/30600)
```suggestion
* Added **provisional** ability to limit Continuation Token size when querying for items. See [PR 30600](https://github.com/Azure/azure-sdk-for-python/pull/30600)
```

2023-06-08 01:48 UTC, merged