Existing signal update
Azure/azure-sdk-for-python pull request #31428
Opened 2023-08-02 08:02 UTC by nemanjarajic

# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

2023-08-02 08:35 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[azure-ai-ml](https://apiview.dev/Assemblies/Review/650e348c98f541cea8e1ad04cc6c30af)

2023-08-14 16:29 UTC, banibrata commented on sdk/ml/azure-ai-ml/azure/ai/ml/_schema/monitoring/input_data.py
> +class StaticInputDataSchema(MonitorInputDataSchema):
Please add experiemental for all the previe classes

2023-08-21 14:52 UTC, needuv commented on sdk/ml/azure-ai-ml/azure/ai/ml/_schema/monitoring/compute.py
> +class ComputeIdentitySchema(metaclass=PatchedSchemaMeta):
as we dicussed last week, we don't need this since compute identity is always `AMLToken`

2023-08-21 15:02 UTC, needuv requested changes

2023-08-21 15:02 UTC, needuv commented on sdk/ml/azure-ai-ml/tests/monitoring/e2etests/test_monitor_schedule.py
>  @pytest.mark.core_sdk_test
please change this mark to point to the production experiences team

2023-08-21 15:02 UTC, needuv commented on sdk/ml/azure-ai-ml/tests/monitoring/e2etests/test_monitor_schedule.py
> +    @pytest.mark.skip()
any reason why we can't enable them in this PR?

2023-08-21 18:58 UTC, nemanjarajic commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/input_data.py
> +class FixedInputData(MonitorInputData):
jobInputType like mltable

2023-08-21 18:59 UTC, nemanjarajic commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/input_data.py
> +        self.job_type = job_type
jobInputType like mltable

2023-08-21 19:02 UTC, nemanjarajic commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/input_data.py
> +class FixedInputData(MonitorInputData):
production and reference data that is sent to service. Decided between the 3 types based on if user is passing data window size, window start/end, or no window

2023-08-21 19:16 UTC, MilesHolland approved these changes

2023-08-21 19:28 UTC, banibrata approved these changes

2023-08-21 21:29 UTC, merged