OneLake datastore fixes
Azure/azure-sdk-for-python pull request #31517
Opened 2023-08-08 18:37 UTC by youngpark

# Description

This PR fixes the serialization issues in OneLakeArtifact and updates datastore service client to 04012023 preview version to support OneLake datastore types.

# All SDK Contribution checklist:
- [X] **The pull request does not introduce [breaking changes]**
- [X] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [X] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [X] Title of the pull request is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [X] Pull request includes test coverage for the included changes.

2023-08-08 19:05 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[azure-ai-ml](https://apiview.dev/Assemblies/Review/616bb198358c4bff96a142bca7f0a577)

2023-08-14 21:44 UTC, diondrapeck requested changes

2023-08-14 21:44 UTC, diondrapeck commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/_datastore/one_lake.py
> +class OneLakeArtifact(RestTranslatableMixin, DictMixin, ABC):
Hi Young, can you add docstrings for these new classes, describing the classes, their params and types similar to the one for OneLakeDatastore below?

2023-08-14 22:28 UTC, vivram approved these changes

2023-08-14 22:29 UTC, vivram commented on sdk/ml/azure-ai-ml/tests/test_configs/datastore/one_lake.yml
> +  artifact_type: lake_house
Was this rename intended?

2023-08-15 00:26 UTC, diondrapeck approved these changes

2023-08-15 00:29 UTC, merged