[ml] Update changelog for 1.11.1 to note security patch
Azure/azure-sdk-for-python pull request #32465
Opened 2023-10-12 18:24 UTC by diondrapeck

# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

2023-10-12 18:57 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[azure-ai-ml](https://apiview.dev/Assemblies/Review/bdc3baba84c740a782a3eebc0e9009f1)

2023-10-12 19:06 UTC, kdestin approved these changes

2023-10-13 16:13 UTC, needuv requested changes

2023-10-13 16:13 UTC, needuv commented on sdk/ml/azure-ai-ml/CHANGELOG.md
> +## 1.11.1 (unreleased)
```suggestion
## 1.11.1 (2023-10-13)
```

2023-10-13 16:26 UTC, needuv approved these changes

2023-10-13 17:14 UTC, merged