Claim Python 3.12 support for ml and ai SDKs
Azure/azure-sdk-for-python pull request #33885
Opened 2024-01-17 19:22 UTC by luigiw

# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

2024-01-17 19:40 UTC, qubitron approved these changes

2024-01-17 19:59 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[azure-ai-ml](https://apiview.dev/Assemblies/Review/09de885a7c58444190fa9c9ae894d36d?revisionId=acad060fe2a9476dbd2903eb28a8de62)

2024-01-18 18:00 UTC, diondrapeck requested changes
Can you

- add a message to the release notes/CHANGELOGs for all three SDKs
- update the supported versions in the package root READMEs which will show up on learn.microsoft.com

https://github.com/Azure/azure-sdk-for-python/blob/fee8bcfda3ce49ef280f302952732ac835de69ef/sdk/ml/azure-ai-ml/README.md?plain=1#L13C1-L14C1
https://github.com/Azure/azure-sdk-for-python/blob/fee8bcfda3ce49ef280f302952732ac835de69ef/sdk/ai/azure-ai-resources/README.md?plain=1#L12C1-L13C1
https://github.com/Azure/azure-sdk-for-python/blob/fee8bcfda3ce49ef280f302952732ac835de69ef/sdk/ai/azure-ai-generative/README.md?plain=1#L11C1-L12C1

2024-01-19 00:00 UTC, luigiw commented
> Can you
> 
> * add a message to the release notes/CHANGELOGs for all three SDKs
> * update the supported versions in the package root READMEs which will show up on learn.microsoft.com
> 
> https://github.com/Azure/azure-sdk-for-python/blob/fee8bcfda3ce49ef280f302952732ac835de69ef/sdk/ml/azure-ai-ml/README.md?plain=1#L13C1-L14C1 https://github.com/Azure/azure-sdk-for-python/blob/fee8bcfda3ce49ef280f302952732ac835de69ef/sdk/ai/azure-ai-resources/README.md?plain=1#L12C1-L13C1 https://github.com/Azure/azure-sdk-for-python/blob/fee8bcfda3ce49ef280f302952732ac835de69ef/sdk/ai/azure-ai-generative/README.md?plain=1#L11C1-L12C1

Good catch. Added.

2024-01-19 00:21 UTC, diondrapeck approved these changes

2024-01-19 00:58 UTC, luigiw commented
/check-enforcer override

2024-01-19 00:59 UTC, merged