Add missing headers to azure-attestation\README.md
Azure/azure-sdk-for-python pull request #33981
Opened 2024-01-24 15:42 UTC by mwynne

# Description

Added sections per #4554. This is a work in progress. 

 @scbedd before I get really invested with the content under the new headers, I just wanted to make sure I'm going in the right direction with this. It's a pretty old issue, and I noticed that a few of the links in the original issue are broken and it appears there has been some refactoring in the repo since. Thanks.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

2024-01-24 15:45 UTC, mwynne commented
@microsoft-github-policy-service agree

2024-01-29 23:12 UTC, scbedd commented on sdk/attestation/azure-mgmt-attestation/README.md
> +## Key Concepts
```suggestion
```

2024-01-29 23:13 UTC, scbedd commented on sdk/attestation/azure-mgmt-attestation/README.md
> +Content TBD
```suggestion
```

2024-01-29 23:13 UTC, scbedd commented on sdk/attestation/azure-mgmt-attestation/README.md
> +TBC
```suggestion
```

2024-01-29 23:14 UTC, scbedd commented on sdk/attestation/azure-mgmt-attestation/README.md
> +Service client calls that result in HttpResponseError with a StatusCode of 401 or 403 often indicate the caller doesn't have sufficient permissions for the specified API. Check the service documentat
```suggestion
Service client calls that result in HttpResponseError with a StatusCode of 401 or 403 often indicate the caller doesn't have sufficient permissions for the specified API. Check the [service documentation](https://learn.microsoft.com/en-us/azure/attestation/) to determine which RBAC roles are needed for the specific request, and ensure the authenticated user or service principal have been granted the appropriate roles on the resource.
```

2024-01-29 23:14 UTC, scbedd requested changes
Few nits cleaning up TBC/TBD and adding a link to the service documentation.

2024-01-30 17:13 UTC, mwynne commented
@scbedd I'm glad I checked before moving ahead with anything else! I addressed your comments in a new commit. Let me know if I missed anything, or if you'd like additional changes. 

I'll go find something else to work on. Since I'm new around here, if there are any issues that no one else wants to volunteer for that you may want to suggest, please let me know.

2024-02-08 02:30 UTC, scbedd approved these changes
Thank you for the contribution @mwynne ! I'm going to ignore this error (which has nothing to do with your PR) and get this merged.

2024-02-08 02:31 UTC, scbedd commented
/check-enforcer override

Overriding as the `mypy` error is most definitively not from this PR.

2024-02-08 02:35 UTC, merged