re-add WorksapceConnection as importable class
Azure/azure-sdk-for-python pull request #35564
Opened 2024-05-09 13:24 UTC by MilesHolland

Perform some minor trickery to allow both `Connection` and `WorkspaceConnection` to be importable classes from the `azure.ai.ml.entities` package to prevent pseudo-breaking changes. (I use the term 'pseudo-breaking' because technically the `WorkspaceConnection` class was experimental and thus name-changeable, but in practice it's been around and relied upon for so long that actually making a breaking change on its name will cause many problems).

2024-05-09 14:13 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[azure-ai-ml](https://apiview.dev/Assemblies/Review/09de885a7c58444190fa9c9ae894d36d?revisionId=4bb124d1d8964fbc8ae5e43fa45ffffa)

2024-05-09 17:39 UTC, ninghu commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py
>      "Connection",
One more thing we need to think about. AutoML folks mentioned that the expiermental warning (from Connection) will show up when ml_client.workspaces.get is called, but ml_client.workspaces.get is not an experimental method. They suggested to remove the experimental warning.

2024-05-09 18:41 UTC, ninghu commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py
>      "Connection",
Just checked their notebook. I guess the experimental warning is probably not from `ml_client.workspaces.get`. Instead, it should be from `output["Subscription ID"] = ml_client.connections._subscription_id`

![image](https://github.com/Azure/azure-sdk-for-python/assets/11171669/2995eb26-253a-45e6-8cd2-b92ca3243f86)

2024-05-09 21:48 UTC, vizhur requested changes
Please undo the rename. After sync with PMs that change was not approved.

2024-06-18 16:55 UTC, closed without merging

2024-06-18 16:55 UTC, MilesHolland commented
Went for different approach from this.