adding changes to env variables access documentation CommandJob & SweepJob
Azure/azure-sdk-for-python pull request #36564
Opened 2024-07-22 16:50 UTC by Alangulo

# Description

- This pull request introduces an important documentation update to the CommandJob class within the command_job.py file. Specifically, it adds a note to clarify how command components, inputs, outputs, and parameters are accessible when using AML. The note emphasizes that these elements are accessible as environment variables, prefixed with AZUREML_PARAMETER_, providing a clearer guideline for users on how to reference these components within their command jobs.

- Update to the SweepJob file, aimed at enhancing the documentation for users working with hyperparameter tuning jobs in Azure Machine Learning. The key change involves adding a note to clarify how inputs, outputs, and parameters are accessible for sweep jobs. This update is designed to provide clearer guidance for users on how to reference these components within their sweep jobs, improving usability, security for the user and reducing potential confusion.

Changes Made:
- Added a note in the CommandJob class documentation to explicitly state that for command components, inputs, outputs, and parameters are accessible as environment variables using the prefix AZUREML_PARAMETER_. This addition aims to improve the usability and understanding of how to work with command jobs in Azure Machine Learning, making it easier for users to reference job components correctly.

- Added a note in the SweepJob class documentation stating that for sweep jobs, inputs, outputs, and parameters are accessible as environment variables using the prefix AZUREML_SWEEP_. This addition aims to make it easier for users to understand how to work with sweep jobs in Azure Machine Learning, specifically in terms of referencing job components correctly.

Relevant Issues:
No specific issues linked, but this change addresses a common point of confusion among users working with command jobs in Azure Machine Learning.

2024-07-23 03:29 UTC, diondrapeck requested changes

2024-07-23 03:29 UTC, diondrapeck commented on sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/command_job.py
> +    Note that for command components, inputs, outputs, and parameters are accessible as environment variables using the prefix AZUREML_PARAMETER_
Can you add a more detailed example? It's not clear what you mean. Same for Sweep Job.

Is it `AZUREML_PARAMETER_OUTPUT`, `AZUREML_PARAMETER_INPUT`?

2024-07-23 18:41 UTC, diondrapeck approved these changes

2024-07-25 23:35 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[azure-ai-ml](https://apiview.dev/Assemblies/Review/09de885a7c58444190fa9c9ae894d36d?revisionId=c897fcf29c2e49b5b5f6169536270246)

2024-07-31 05:34 UTC, luigiw approved these changes

2024-07-31 07:39 UTC, kingernupur approved these changes

2024-08-06 04:15 UTC, kingernupur approved these changes

2024-08-08 19:19 UTC, diondrapeck commented
/check-enforcer override

2024-08-09 01:29 UTC, wangchao1230 approved these changes

2024-08-09 16:25 UTC, diondrapeck commented
/check-enforcer override

2024-08-10 00:09 UTC, merged