[communication] - [sms] - Splitting int and public cloud tests
Azure/azure-sdk-for-python pull request #37498
Opened 2024-09-20 11:23 UTC by dinazavyr

# Description

Splitting int and public cloud tests.
Int is not stable and it is blocking PRs most of the time.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

2024-09-20 11:23 UTC, dinazavyr commented
/azp run prepare-pipelines

2024-09-20 12:18 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2024-09-23 07:51 UTC, gfeitosa-msft approved these changes

2024-09-23 07:53 UTC, gfeitosa-msft requested changes

2024-09-23 08:22 UTC, dinazavyr commented
/azp run prepare-pipelines

2024-09-23 08:22 UTC, dinazavyr commented on sdk/communication/azure-communication-sms/tests_int.yml
> +trigger: none
changed the file name.

2024-09-23 11:03 UTC, gfeitosa-msft approved these changes

2024-09-23 11:04 UTC, merged