Fix 'NoneType' object has no attribute when querying during Session not available retry
Azure/azure-sdk-for-python pull request #37578
Opened 2024-09-25 21:55 UTC by bambriz

# Description

When Session Retry, Timeout Failover, and Endpoint Discovery retry policies are triggered and do no successfully retry during a Query, a bug occurs that raises a 'NoneType' object has no attribute from a request object. This was caused from the request to fetch the queried items returning back to the base request to start the query. Instead of returning the Cosmos Exception from not successfully retrying, the retry would happen again for the base query request, but the base query request does not have a reference to the Request Object (This is where the 'NoneType' object has no attribute error comes from). This is fixed by allowing the cosmos exception to surface by not retrying at the base request since we already used up the retry attempts while fetching the items during the query.

2024-09-25 21:57 UTC, bambriz commented
/azp run python - cosmos - ci

2024-09-25 22:19 UTC, azure-sdk commented
**API change check**

API changes are not detected in this pull request.

2024-09-27 16:44 UTC, simorenoh commented
/azp run python - cosmos - tests

2024-09-27 19:34 UTC, allenkim0129 requested changes

2024-09-27 19:34 UTC, allenkim0129 commented on sdk/cosmos/azure-cosmos/test/test_query.py
> +from azure.cosmos import http_constants, DatabaseProxy,_retry_utility, _endpoint_discovery_retry_policy
`_retry_utility` has already been imported in line 11. Please remove this and use `retry_utility` instead

2024-09-27 19:34 UTC, allenkim0129 commented on sdk/cosmos/azure-cosmos/test/test_query_async.py
> +from azure.cosmos.aio import CosmosClient, DatabaseProxy, ContainerProxy, _retry_utility_async
`_retry_utility_async` has been imported already in line 12. You can remove this import and use `retry_utility` instead

2024-09-27 19:34 UTC, allenkim0129 commented on sdk/cosmos/azure-cosmos/test/test_query_async.py
> +        _retry_utility_async.ExecuteFunctionAsync = self.OriginalExecuteFunction
Why was this assignment needed when you set `ExecuteFunctionAsync` in line 968 again?

Please remove this line if it is not necessary.

2024-09-30 19:24 UTC, bambriz commented
/azp run python - cosmos - tests

2024-09-30 21:51 UTC, bambriz commented
/azp run python - cosmos - tests

2024-10-02 11:37 UTC, philipthomas-MSFT approved these changes

2024-10-02 17:27 UTC, simorenoh approved these changes

2024-10-02 18:53 UTC, allenkim0129 approved these changes

2024-10-02 19:53 UTC, merged